version: '3.8'

services:
  web:
    build: .
    ports:
      - "8098:8098"
    volumes:
      - .:/app
    environment:
      - PRIVATE_KEY=
      - CONTRACT_ADDRESS=
      - SECRET_KEY=f3cfe9ed8fae309f02079dbf
